/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-10-28 15:00:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Welcome to Shopify Online Shopping Store</title>\r\n");
      out.write("<!--inline css for  homepage -->\r\n");
      out.write("	<style>\r\n");
      out.write("		* {\r\n");
      out.write("			margin: 0;\r\n");
      out.write("			padding: 0;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.navbar {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			position: sticky;\r\n");
      out.write("			top: 0;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.background {\r\n");
      out.write("			background:#bfb9a3;\r\n");
      out.write("			background-blend-mode: darken;\r\n");
      out.write("			background-size: cover;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.nav-list {\r\n");
      out.write("			width: 70%;\r\n");
      out.write("			display: flex;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		.nav-list li {\r\n");
      out.write("			list-style: none;\r\n");
      out.write("			padding: 26px 30px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.nav-list li a {\r\n");
      out.write("			text-decoration: none;\r\n");
      out.write("			color: #3b2d06;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.nav-list li a:hover {\r\n");
      out.write("			color: grey;\r\n");
      out.write("		}\r\n");
      out.write("		.nav-list li:last-child {\r\n");
      out.write("            margin-left: auto; \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("		.rightnav {\r\n");
      out.write("			width: 30%;\r\n");
      out.write("			text-align: right;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		.firstsection {\r\n");
      out.write("			background-color:#ede7e1 ;\r\n");
      out.write("			height: 400px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.secondsection {\r\n");
      out.write("			background-color:#c4c3bc;\r\n");
      out.write("			height: 400px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.box-main {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			color: black;\r\n");
      out.write("			max-width: 80%;\r\n");
      out.write("			margin: auto;\r\n");
      out.write("			height: 80%;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.firsthalf {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			display: flex;\r\n");
      out.write("			flex-direction: column;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.secondhalf {\r\n");
      out.write("			width: 30%;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.secondhalf img {\r\n");
      out.write("			width: 70%;\r\n");
      out.write("			border: 4px solid white;\r\n");
      out.write("			border-radius: 150px;\r\n");
      out.write("			display: block;\r\n");
      out.write("			margin: auto;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.text-big {\r\n");
      out.write("			font-family: 'Piazzolla', serif;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			font-size: 35px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.text-small {\r\n");
      out.write("			font-size: 18px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.btn {\r\n");
      out.write("			padding: 8px 20px;\r\n");
      out.write("			margin: 7px 0;\r\n");
      out.write("			border: 2px solid white;\r\n");
      out.write("			border-radius: 8px;\r\n");
      out.write("			background: none;\r\n");
      out.write("			color: white;\r\n");
      out.write("			cursor: pointer;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.btn-sm {\r\n");
      out.write("			padding: 6px 10px;\r\n");
      out.write("			vertical-align: middle;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.section {\r\n");
      out.write("			height: 400px;\r\n");
      out.write("			display: flex;\r\n");
      out.write("			align-items: center;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			max-width: 90%;\r\n");
      out.write("			margin: auto;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.section-Left {\r\n");
      out.write("			flex-direction: row-reverse;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.paras {\r\n");
      out.write("			padding: 0px 65px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.thumbnail img {\r\n");
      out.write("			width: 250px;\r\n");
      out.write("			border: 2px solid black;\r\n");
      out.write("			border-radius: 26px;\r\n");
      out.write("			margin-top: 19px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.center {\r\n");
      out.write("			text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.text-footer {\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			padding: 30px 0;\r\n");
      out.write("			font-family: 'Ubuntu', sans-serif;\r\n");
      out.write("			display: flex;\r\n");
      out.write("			justify-content: center;\r\n");
      out.write("			color: white;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"navbar background\">\r\n");
      out.write("		<ul class=\"nav-list\">\r\n");
      out.write("		<!-- Homepage -->\r\n");
      out.write("			<li><a href=\"#web\">Buy Products</a></li>\r\n");
      out.write("			<li><a href=\"#program\">Sell Products</a></li>\r\n");
      out.write("			<li><a href=\"customerquestioninsert.jsp\">Ask Question</a></li>\r\n");
      out.write("			<li><a href=\"#login\">Login</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"firstsection\">\r\n");
      out.write("		<div class=\"box-main\">\r\n");
      out.write("			<div class=\"firstHalf\">\r\n");
      out.write("				<h1 class=\"text-big\" id=\"web\">Welcome to Shopify Online Shopping Store</h1>\r\n");
      out.write("				<p class=\"text-small\">\r\n");
      out.write("					Shop with us\r\n");
      out.write("				</p>\r\n");
      out.write("                      \r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"secondsection\">\r\n");
      out.write("		<div class=\"box-main\">\r\n");
      out.write("			<div class=\"firstHalf\">\r\n");
      out.write("				<h1 class=\"text-big\" id=\"program\">\r\n");
      out.write("					Largest online shopping store in Sri Lanka</h1>\r\n");
      out.write("                   <p>With Lino we endeavour to build a destination in Sri Lanka where customers get more of what they want - Best selection, low prices, fast and reliable delivery, and a trusted and convenient online shopping experience. We are committed to ensuring you a safe and secure online ordering experience.\r\n");
      out.write("\r\n");
      out.write("                        076 122 6830\r\n");
      out.write("                        076 546 6929\r\n");
      out.write("                        \"Sinhala, English, Tamil\"\r\n");
      out.write("                         Monday - Friday (10.00 am - 6.00 pm)\r\n");
      out.write("                         Saturday (11.00 am - 1.00 pm)\r\n");
      out.write("                         Sunday (Closed)</p>\r\n");
      out.write("				\r\n");
      out.write("				<p class=\"text-small\">\r\n");
      out.write("					Shop with us\r\n");
      out.write("					\r\n");
      out.write("				</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"background\">\r\n");
      out.write("		<p class=\"text-footer\">\r\n");
      out.write("			Copyright ©-All rights are reserved\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
